#ifndef CHILD_CONTROLS_H
#define CHILD_CONTROLS_H

#define ID_IP_ADDR_LABEL        100
#define ID_IP_TXT               101
#define ID_BTTN_CONNECT         102
//#define ID_STATUS_LABEL         103
//#define ID_STATUS_TXT           104
#define ID_BTTN_DISCONNECT      105
#define ID_ACTION_LABEL         106
#define ID_ACTION_COMBOBOX      107
#define ID_BTTN_GET_PROCS       108
#define ID_PROCLIST_LABEL       109
#define ID_PROCLIST_LISTVIEW    110
#define ID_BTTN_CLEAR_LISTVIEW  111
#define ID_STATUS_BAR           112
#define ID_KILL_SELECTED        113

HWND LABEL_IP_ADDR;
HWND TXT_IP_ADDR;
HWND BTTN_CONNECT;
//HWND LABEL_STATUS;
//HWND TXT_STATUS;
HWND BTTN_DISCONNECT;
HWND LABEL_ACTION;
HWND COMBOBOX_ACTION;
HWND BTTN_GET_PROCS;
HWND LABEL_PROCLIST;
HWND LISTVIEW_PROCLIST;
HWND BTTN_CLEAR_LISTVIEW;
HWND STATUS_BAR;
HWND BTTN_KILL_SELECTED;

LVITEM LvItem;
LVCOLUMN LvCol;

#endif // CHILD_CONTROLS_H
